# Generated by Django 3.1.1 on 2020-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201117_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
