# Generated by Django 3.1.13 on 2022-01-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20201119_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_address', to='Users.address'),
        ),
    ]
