# Generated by Django 3.1.13 on 2022-01-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20220106_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
    ]
