# Generated by Django 3.1.13 on 2022-02-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20220206_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_address', to='Users.address'),
        ),
    ]
