# Generated by Django 3.1.13 on 2022-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20220106_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Status',
            new_name='fullfillment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='initiated', max_length=50),
        ),
    ]
