# Generated by Django 3.1.13 on 2022-01-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_auto_20220108_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Variation',
            new_name='variation_id',
        ),
    ]
