# Generated by Django 3.1.13 on 2022-02-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_auto_20220212_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='extra_charges',
            new_name='shipping_charges',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
