# Generated by Django 3.1.13 on 2022-02-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_auto_20220212_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
    ]
