# Generated by Django 3.1.1 on 2020-11-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verified_by',
            field=models.IntegerField(choices=[(1, 'phone'), (2, 'email')]),
        ),
    ]
