# Generated by Django 3.1.13 on 2022-01-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Town',
            new_name='town',
        ),
    ]
