# Generated by Django 3.1.13 on 2022-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20220108_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Addresses',
            field=models.ManyToManyField(blank=True, null=True, to='Users.Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='customer',
            name='verified_by',
            field=models.IntegerField(blank=True, choices=[(1, 'phone'), (2, 'email')], null=True),
        ),
    ]
