# Generated by Django 3.1.13 on 2022-02-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20220219_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Addresses',
            field=models.ManyToManyField(blank=True, to='Users.Address'),
        ),
    ]
