# Generated by Django 3.1.1 on 2020-11-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.ordergroup'),
        ),
    ]
