# Generated by Django 3.1.1 on 2020-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20201118_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Status',
            field=models.CharField(default='Unpaid', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Variation',
            field=models.CharField(max_length=50),
        ),
    ]
