# Generated by Django 3.1.13 on 2022-01-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20201122_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('0', 'stripe_checkout'), ('1', 'PaymentIntent')], default='1', max_length=50),
        ),
    ]
