# Generated by Django 3.1.13 on 2022-02-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20220206_1710'),
        ('Orders', '0011_order_fulfillment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='fullfillment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('Unfulfilled', 'Unfulfilled'), ('PartiallyFulfilled', 'PartiallyFulfilled'), ('Fulfilled', 'Fulfilled')], default='Unfulfilled', max_length=50),
        ),
    ]
